//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Password {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsUser : DataSet {
        
        private UserIDDataTable tableUserID;
        
        public dsUser() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsUser(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["UserID"] != null)) {
                    this.Tables.Add(new UserIDDataTable(ds.Tables["UserID"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public UserIDDataTable UserID {
            get {
                return this.tableUserID;
            }
        }
        
        public override DataSet Clone() {
            dsUser cln = ((dsUser)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["UserID"] != null)) {
                this.Tables.Add(new UserIDDataTable(ds.Tables["UserID"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableUserID = ((UserIDDataTable)(this.Tables["UserID"]));
            if ((this.tableUserID != null)) {
                this.tableUserID.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsUser";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsUser.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableUserID = new UserIDDataTable();
            this.Tables.Add(this.tableUserID);
        }
        
        private bool ShouldSerializeUserID() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void UserIDRowChangeEventHandler(object sender, UserIDRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UserIDDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnID_Number;
            
            private DataColumn columnUser_Name;
            
            private DataColumn columnPassword;
            
            internal UserIDDataTable() : 
                    base("UserID") {
                this.InitClass();
            }
            
            internal UserIDDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ID_NumberColumn {
                get {
                    return this.columnID_Number;
                }
            }
            
            internal DataColumn User_NameColumn {
                get {
                    return this.columnUser_Name;
                }
            }
            
            internal DataColumn PasswordColumn {
                get {
                    return this.columnPassword;
                }
            }
            
            public UserIDRow this[int index] {
                get {
                    return ((UserIDRow)(this.Rows[index]));
                }
            }
            
            public event UserIDRowChangeEventHandler UserIDRowChanged;
            
            public event UserIDRowChangeEventHandler UserIDRowChanging;
            
            public event UserIDRowChangeEventHandler UserIDRowDeleted;
            
            public event UserIDRowChangeEventHandler UserIDRowDeleting;
            
            public void AddUserIDRow(UserIDRow row) {
                this.Rows.Add(row);
            }
            
            public UserIDRow AddUserIDRow(int ID_Number, string User_Name, string Password) {
                UserIDRow rowUserIDRow = ((UserIDRow)(this.NewRow()));
                rowUserIDRow.ItemArray = new object[] {
                        ID_Number,
                        User_Name,
                        Password};
                this.Rows.Add(rowUserIDRow);
                return rowUserIDRow;
            }
            
            public UserIDRow FindByID_Number(int ID_Number) {
                return ((UserIDRow)(this.Rows.Find(new object[] {
                            ID_Number})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                UserIDDataTable cln = ((UserIDDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new UserIDDataTable();
            }
            
            internal void InitVars() {
                this.columnID_Number = this.Columns["ID Number"];
                this.columnUser_Name = this.Columns["User Name"];
                this.columnPassword = this.Columns["Password"];
            }
            
            private void InitClass() {
                this.columnID_Number = new DataColumn("ID Number", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnID_Number);
                this.columnUser_Name = new DataColumn("User Name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUser_Name);
                this.columnPassword = new DataColumn("Password", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPassword);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnID_Number}, true));
                this.columnID_Number.AllowDBNull = false;
                this.columnID_Number.Unique = true;
            }
            
            public UserIDRow NewUserIDRow() {
                return ((UserIDRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new UserIDRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(UserIDRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.UserIDRowChanged != null)) {
                    this.UserIDRowChanged(this, new UserIDRowChangeEvent(((UserIDRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.UserIDRowChanging != null)) {
                    this.UserIDRowChanging(this, new UserIDRowChangeEvent(((UserIDRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.UserIDRowDeleted != null)) {
                    this.UserIDRowDeleted(this, new UserIDRowChangeEvent(((UserIDRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.UserIDRowDeleting != null)) {
                    this.UserIDRowDeleting(this, new UserIDRowChangeEvent(((UserIDRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveUserIDRow(UserIDRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UserIDRow : DataRow {
            
            private UserIDDataTable tableUserID;
            
            internal UserIDRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableUserID = ((UserIDDataTable)(this.Table));
            }
            
            public int ID_Number {
                get {
                    return ((int)(this[this.tableUserID.ID_NumberColumn]));
                }
                set {
                    this[this.tableUserID.ID_NumberColumn] = value;
                }
            }
            
            public string User_Name {
                get {
                    try {
                        return ((string)(this[this.tableUserID.User_NameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUserID.User_NameColumn] = value;
                }
            }
            
            public string Password {
                get {
                    try {
                        return ((string)(this[this.tableUserID.PasswordColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUserID.PasswordColumn] = value;
                }
            }
            
            public bool IsUser_NameNull() {
                return this.IsNull(this.tableUserID.User_NameColumn);
            }
            
            public void SetUser_NameNull() {
                this[this.tableUserID.User_NameColumn] = System.Convert.DBNull;
            }
            
            public bool IsPasswordNull() {
                return this.IsNull(this.tableUserID.PasswordColumn);
            }
            
            public void SetPasswordNull() {
                this[this.tableUserID.PasswordColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UserIDRowChangeEvent : EventArgs {
            
            private UserIDRow eventRow;
            
            private DataRowAction eventAction;
            
            public UserIDRowChangeEvent(UserIDRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public UserIDRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
